-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS "vipUsers",
    "sponsorTimes",
    "userNames",
    "categoryVotes",
    "lockCategories",
    "warnings",
    "shadowBannedUsers",
    "videoInfo",
    "unlistedVideos",
    "config",
    "archivedSponsorTimes",
    "ratings",
    "userFeatures",
    "shadowBannedIPs",
    "titles",
    "titleVotes",
    "thumbnails",
    "thumbnailTimestamps",
    "thumbnailVotes";